image: docker:latest

services:
  - docker:dind

variables:
  IMAGE_GIT_REF_TAG: $CI_REGISTRY_IMAGE:git-$CI_COMMIT_SHORT_SHA
  IMAGE_RELEASE_TAG: $CI_REGISTRY_IMAGE:$CI_COMMIT_TAG
  IMAGE_LATEST_TAG: $CI_REGISTRY_IMAGE:latest

stages:
  - release

publish-image-from-master:
  stage: release
  before_script:
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY
  script:
    - docker build -t $IMAGE_LATEST_TAG .
    - docker push $CI_REGISTRY_IMAGE
